# Generated by Django 6.0.5 on 2026-06-03 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de fim')),
                ('vagas', models.PositiveIntegerField(verbose_name='Vagas')),
                ('tipo', models.CharField(choices=[('PALESTRA', 'Palestra'), ('WORKSHOP', 'Workshop'), ('MINICURSO', 'Minicurso'), ('SEMINARIO', 'Seminário'), ('OUTRO', 'Outro')], default='PALESTRA', max_length=30, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('categorias', models.ManyToManyField(blank=True, to='eventos.categoria', verbose_name='Categorias')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de inscrição')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento', verbose_name='Evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL, verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-data_inscricao'],
                'unique_together': {('evento', 'participante')},
            },
        ),
    ]
